# -*- coding: utf-8 -*-
"""программный модуль.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRIQ5gStPhLsCVixkHqM6PmoY_1dEk7S
"""

class Participant:
    def __init__(self, name: str, age: int, article_title: str):
        self.name = name
        self.age = age
        self.article_title = article_title

    def __str__(self):
        return f"{self.name}, {self.age} лет, статья: {self.article_title}"


class ParticipantManager:
    def __init__(self):
        self.participants = []

    # Добавление участника
    def add_participant(self, name, age, article_title):
        if not self.validate(name, age):
            print("Ошибка: некорректные данные")
            return

        participant = Participant(name, age, article_title)
        self.participants.append(participant)
        print("Участник добавлен")

    # Валидация данных
    def validate(self, name, age):
        if not name or not isinstance(name, str):
            return False
        if not isinstance(age, int) or age <= 0:
            return False
        return True

    # Поиск участника
    def find_by_name(self, name):
        return [p for p in self.participants if p.name.lower() == name.lower()]

    # Фильтрация по возрасту
    def filter_by_age(self, min_age):
        return [p for p in self.participants if p.age >= min_age]

    # Статистика
    def get_statistics(self):
        if not self.participants:
            return "Нет данных"

        avg_age = sum(p.age for p in self.participants) / len(self.participants)
        return {
            "count": len(self.participants),
            "average_age": avg_age
        }

    # Вывод всех участников
    def show_all(self):
        for p in self.participants:
            print(p)


# Основная программа
def main():
    manager = ParticipantManager()

    while True:
        print("\n1. Добавить участника")
        print("2. Найти участника")
        print("3. Фильтр по возрасту")
        print("4. Статистика")
        print("5. Показать всех")
        print("0. Выход")

        choice = input("Выбор: ")

        if choice == "1":
            name = input("Имя: ")
            age = int(input("Возраст: "))
            article = input("Название статьи: ")
            manager.add_participant(name, age, article)

        elif choice == "2":
            name = input("Введите имя: ")
            results = manager.find_by_name(name)
            for r in results:
                print(r)

        elif choice == "3":
            age = int(input("Минимальный возраст: "))
            results = manager.filter_by_age(age)
            for r in results:
                print(r)

        elif choice == "4":
            print(manager.get_statistics())

        elif choice == "5":
            manager.show_all()

        elif choice == "0":
            break

        else:
            print("Неверный ввод")


if __name__ == "__main__":
    main()