# -*- coding: utf-8 -*-
"""программный модуль.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRIQ5gStPhLsCVixkHqM6PmoY_1dEk7S
"""

class BankAccount:
    def __init__(self, owner: str):
        self.owner = owner
        self.balance = 0

    def deposit(self, amount: int):
        if amount <= 0:
            return "Ошибка: сумма должна быть больше 0"

        self.balance += amount
        return f"Пополнение успешно. Баланс: {self.balance}"

    def withdraw(self, amount: int):
        if amount <= 0:
            return "Ошибка: сумма должна быть больше 0"

        if amount > self.balance:
            return "Ошибка: недостаточно средств"

        self.balance -= amount
        return f"Снятие успешно. Баланс: {self.balance}"

    def get_balance(self):
        return f"Текущий баланс: {self.balance}"


def main():
    name = input("Введите имя владельца счёта: ")
    account = BankAccount(name)

    while True:
        print("\n--- МЕНЮ ---")
        print("1. Пополнить счёт")
        print("2. Снять деньги")
        print("3. Показать баланс")
        print("0. Выход")

        choice = input("Выберите действие: ")

        if choice == "1":
            try:
                amount = int(input("Введите сумму пополнения: "))
                print(account.deposit(amount))
            except ValueError:
                print("Ошибка: нужно ввести число")

        elif choice == "2":
            try:
                amount = int(input("Введите сумму снятия: "))
                print(account.withdraw(amount))
            except ValueError:
                print("Ошибка: нужно ввести число")

        elif choice == "3":
            print(account.get_balance())

        elif choice == "0":
            print("Выход из программы")
            break

        else:
            print("Неверный выбор")


if __name__ == "__main__":
    main()